/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calculator */

#ifndef _Included_Calculator
#define _Included_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calculator
 * Method:    ADDNUMBERS
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_ADDNUMBERS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    SUBNUMBERS
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_SUBNUMBERS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    MULNUMBERS
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_MULNUMBERS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Calculator
 * Method:    DIVNUMBERS
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Calculator_DIVNUMBERS
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
